services:
  - type: web
    name: stock-signal-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
    plan: free
    branch: master
    autoDeploy: true

staticSites:
  - name: stock-signal-dashboard
    buildCommand: echo done
    staticPublishPath: ./docs
    branch: master
    plan: free
    autoDeploy: true
